# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'settings.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_SettingsDialog(object):
    def setupUi(self, SettingsDialog):
        if not SettingsDialog.objectName():
            SettingsDialog.setObjectName(u"SettingsDialog")
        SettingsDialog.resize(720, 460)
        self.verticalLayout = QVBoxLayout(SettingsDialog)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.splitter = QSplitter(SettingsDialog)
        self.splitter.setObjectName(u"splitter")
        self.splitter.setOrientation(Qt.Horizontal)
        self.categoryListWidget = QListWidget(self.splitter)
        self.categoryListWidget.setObjectName(u"categoryListWidget")
        self.categoryListWidget.setFrameShape(QFrame.NoFrame)
        self.categoryListWidget.setAlternatingRowColors(True)
        self.categoryListWidget.setSelectionMode(QAbstractItemView.SingleSelection)
        self.categoryListWidget.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.categoryListWidget.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.categoryListWidget.setUniformItemSizes(True)
        item = QListWidgetItem()
        self.categoryListWidget.addItem(item)
        item = QListWidgetItem()
        self.categoryListWidget.addItem(item)
        item = QListWidgetItem()
        self.categoryListWidget.addItem(item)
        self.stackedWidget = QStackedWidget(self.splitter)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.generalPage = QWidget()
        self.generalPage.setObjectName(u"generalPage")
        self.generalLayout = QVBoxLayout(self.generalPage)
        self.generalLayout.setObjectName(u"generalLayout")
        self.autoCloseCheckBox = QCheckBox(self.generalPage)
        self.autoCloseCheckBox.setObjectName(u"autoCloseCheckBox")
        self.generalLayout.addWidget(self.autoCloseCheckBox)
        self.closeTimeoutLayout = QHBoxLayout()
        self.closeTimeoutLayout.setObjectName(u"closeTimeoutLayout")
        self.closeTimeoutLabel = QLabel(self.generalPage)
        self.closeTimeoutLabel.setObjectName(u"closeTimeoutLabel")
        self.closeTimeoutLayout.addWidget(self.closeTimeoutLabel)
        self.closeTimeoutSpinBox = QSpinBox(self.generalPage)
        self.closeTimeoutSpinBox.setObjectName(u"closeTimeoutSpinBox")
        self.closeTimeoutSpinBox.setMinimum(1)
        self.closeTimeoutSpinBox.setMaximum(240)
        self.closeTimeoutLayout.addWidget(self.closeTimeoutSpinBox)
        self.generalLayout.addLayout(self.closeTimeoutLayout)
        self.saveWindowStateCheckBox = QCheckBox(self.generalPage)
        self.saveWindowStateCheckBox.setObjectName(u"saveWindowStateCheckBox")
        self.generalLayout.addWidget(self.saveWindowStateCheckBox)
        self.restoreSessionCheckBox = QCheckBox(self.generalPage)
        self.restoreSessionCheckBox.setObjectName(u"restoreSessionCheckBox")
        self.generalLayout.addWidget(self.restoreSessionCheckBox)
        self.generalLayout.addItem(QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding))
        self.stackedWidget.addWidget(self.generalPage)
        self.interfacePage = QWidget()
        self.interfacePage.setObjectName(u"interfacePage")
        self.interfaceLayout = QVBoxLayout(self.interfacePage)
        self.interfaceLayout.setObjectName(u"interfaceLayout")
        self.showStatusBarCheckBox = QCheckBox(self.interfacePage)
        self.showStatusBarCheckBox.setObjectName(u"showStatusBarCheckBox")
        self.interfaceLayout.addWidget(self.showStatusBarCheckBox)
        self.fontSizeLayout = QHBoxLayout()
        self.fontSizeLayout.setObjectName(u"fontSizeLayout")
        self.fontSizeLabel = QLabel(self.interfacePage)
        self.fontSizeLabel.setObjectName(u"fontSizeLabel")
        self.fontSizeLayout.addWidget(self.fontSizeLabel)
        self.fontSizeComboBox = QComboBox(self.interfacePage)
        self.fontSizeComboBox.setObjectName(u"fontSizeComboBox")
        self.fontSizeComboBox.addItem("")
        self.fontSizeComboBox.addItem("")
        self.fontSizeComboBox.addItem("")
        self.fontSizeLayout.addWidget(self.fontSizeComboBox)
        self.interfaceLayout.addLayout(self.fontSizeLayout)
        self.themeLayout = QHBoxLayout()
        self.themeLayout.setObjectName(u"themeLayout")
        self.themeLabel = QLabel(self.interfacePage)
        self.themeLabel.setObjectName(u"themeLabel")
        self.themeLayout.addWidget(self.themeLabel)
        self.themeComboBox = QComboBox(self.interfacePage)
        self.themeComboBox.setObjectName(u"themeComboBox")
        self.themeComboBox.addItem("")
        self.themeComboBox.addItem("")
        self.themeLayout.addWidget(self.themeComboBox)
        self.interfaceLayout.addLayout(self.themeLayout)
        self.interfaceLayout.addItem(QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding))
        self.stackedWidget.addWidget(self.interfacePage)
        self.notificationsPage = QWidget()
        self.notificationsPage.setObjectName(u"notificationsPage")
        self.notificationsLayout = QVBoxLayout(self.notificationsPage)
        self.notificationsLayout.setObjectName(u"notificationsLayout")
        self.enableNotificationsCheckBox = QCheckBox(self.notificationsPage)
        self.enableNotificationsCheckBox.setObjectName(u"enableNotificationsCheckBox")
        self.notificationsLayout.addWidget(self.enableNotificationsCheckBox)
        self.notificationsTimeoutLayout = QHBoxLayout()
        self.notificationsTimeoutLayout.setObjectName(u"notificationsTimeoutLayout")
        self.notificationsTimeoutLabel = QLabel(self.notificationsPage)
        self.notificationsTimeoutLabel.setObjectName(u"notificationsTimeoutLabel")
        self.notificationsTimeoutLayout.addWidget(self.notificationsTimeoutLabel)
        self.notificationsTimeoutSpinBox = QSpinBox(self.notificationsPage)
        self.notificationsTimeoutSpinBox.setObjectName(u"notificationsTimeoutSpinBox")
        self.notificationsTimeoutSpinBox.setMinimum(1)
        self.notificationsTimeoutSpinBox.setMaximum(120)
        self.notificationsTimeoutLayout.addWidget(self.notificationsTimeoutSpinBox)
        self.notificationsLayout.addLayout(self.notificationsTimeoutLayout)
        self.notificationsLayout.addItem(QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding))
        self.stackedWidget.addWidget(self.notificationsPage)

        self.verticalLayout.addWidget(self.splitter)

        self.buttonLayout = QHBoxLayout()
        self.buttonLayout.setObjectName(u"buttonLayout")
        self.buttonSpacer = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.buttonLayout.addItem(self.buttonSpacer)
        self.acceptPushButton = QPushButton(SettingsDialog)
        self.acceptPushButton.setObjectName(u"acceptPushButton")
        self.buttonLayout.addWidget(self.acceptPushButton)
        self.cancelPushButton = QPushButton(SettingsDialog)
        self.cancelPushButton.setObjectName(u"cancelPushButton")
        self.buttonLayout.addWidget(self.cancelPushButton)
        self.applyPushButton = QPushButton(SettingsDialog)
        self.applyPushButton.setObjectName(u"applyPushButton")
        self.buttonLayout.addWidget(self.applyPushButton)

        self.verticalLayout.addLayout(self.buttonLayout)

        self.retranslateUi(SettingsDialog)

        QMetaObject.connectSlotsByName(SettingsDialog)

    # setupUi

    def retranslateUi(self, SettingsDialog):
        SettingsDialog.setWindowTitle(QCoreApplication.translate("SettingsDialog", u"\u041d\u0430\u0441\u0442\u0440\u043e\u0439\u043a\u0438", None))
        __sortingEnabled = self.categoryListWidget.isSortingEnabled()
        self.categoryListWidget.setSortingEnabled(False)
        ___qlistwidgetitem = self.categoryListWidget.item(0)
        ___qlistwidgetitem.setText(QCoreApplication.translate("SettingsDialog", u"\u041e\u0431\u0449\u0438\u0435", None))
        ___qlistwidgetitem1 = self.categoryListWidget.item(1)
        ___qlistwidgetitem1.setText(QCoreApplication.translate("SettingsDialog", u"\u0418\u043d\u0442\u0435\u0440\u0444\u0435\u0439\u0441", None))
        ___qlistwidgetitem2 = self.categoryListWidget.item(2)
        ___qlistwidgetitem2.setText(QCoreApplication.translate("SettingsDialog", u"\u0423\u0432\u0435\u0434\u043e\u043c\u043b\u0435\u043d\u0438\u044f", None))
        self.categoryListWidget.setSortingEnabled(__sortingEnabled)
        self.autoCloseCheckBox.setText(QCoreApplication.translate("SettingsDialog", u"\u0417\u0430\u043f\u0443\u0441\u043a\u0430\u0442\u044c \u0442\u0430\u0439\u043c\u0435\u0440 \u0430\u0432\u0442\u043e\u0437\u0430\u043a\u0440\u044b\u0442\u0438\u044f", None))
        self.closeTimeoutLabel.setText(QCoreApplication.translate("SettingsDialog", u"\u0427\u0435\u0440\u0435\u0437, \u043c\u0438\u043d", None))
        self.saveWindowStateCheckBox.setText(QCoreApplication.translate("SettingsDialog", u"\u0417\u0430\u043f\u043e\u043c\u0438\u043d\u0430\u0442\u044c \u0440\u0430\u0441\u043f\u043e\u043b\u043e\u0436\u0435\u043d\u0438\u0435 \u043e\u043a\u043d\u0430", None))
        self.restoreSessionCheckBox.setText(QCoreApplication.translate("SettingsDialog", u"\u0412\u043e\u0441\u0441\u0442\u0430\u043d\u0430\u0432\u043b\u0438\u0432\u0430\u0442\u044c \u043f\u043e\u0441\u043b\u0435\u0434\u043d\u044e\u044e \u0441\u0435\u0441\u0441\u0438\u044e", None))
        self.showStatusBarCheckBox.setText(QCoreApplication.translate("SettingsDialog", u"\u041f\u043e\u043a\u0430\u0437\u044b\u0432\u0430\u0442\u044c \u0441\u0442\u0440\u043e\u043a\u0443 \u0441\u043e\u0441\u0442\u043e\u044f\u043d\u0438\u044f", None))
        self.fontSizeLabel.setText(QCoreApplication.translate("SettingsDialog", u"\u0420\u0430\u0437\u043c\u0435\u0440 \u0448\u0440\u0438\u0444\u0442\u0430", None))
        self.fontSizeComboBox.setItemText(0, QCoreApplication.translate("SettingsDialog", u"\u041c\u0435\u043b\u043a\u0438\u0439", None))
        self.fontSizeComboBox.setItemText(1, QCoreApplication.translate("SettingsDialog", u"\u041e\u0431\u044b\u0447\u043d\u044b\u0439", None))
        self.fontSizeComboBox.setItemText(2, QCoreApplication.translate("SettingsDialog", u"\u041a\u0440\u0443\u043f\u043d\u044b\u0439", None))
        self.themeLabel.setText(QCoreApplication.translate("SettingsDialog", u"\u0422\u0435\u043c\u0430 \u043e\u0444\u043e\u0440\u043c\u043b\u0435\u043d\u0438\u044f", None))
        self.themeComboBox.setItemText(0, QCoreApplication.translate("SettingsDialog", u"\u0421\u0432\u0435\u0442\u043b\u0430\u044f", None))
        self.themeComboBox.setItemText(1, QCoreApplication.translate("SettingsDialog", u"\u0422\u0451\u043c\u043d\u0430\u044f", None))
        self.enableNotificationsCheckBox.setText(QCoreApplication.translate("SettingsDialog", u"\u041f\u043e\u043a\u0430\u0437\u044b\u0432\u0430\u0442\u044c \u0432\u0441\u043f\u043b\u044b\u0432\u0430\u044e\u0449\u0438\u0435 \u0443\u0432\u0435\u0434\u043e\u043c\u043b\u0435\u043d\u0438\u044f", None))
        self.notificationsTimeoutLabel.setText(QCoreApplication.translate("SettingsDialog", u"\u0412\u0440\u0435\u043c\u044f \u043f\u043e\u043a\u0430\u0437\u0430, \u0441\u0435\u043a", None))
        self.acceptPushButton.setText(QCoreApplication.translate("SettingsDialog", u"\u041e\u043a", None))
        self.cancelPushButton.setText(QCoreApplication.translate("SettingsDialog", u"\u041e\u0442\u043c\u0435\u043d\u0430", None))
        self.applyPushButton.setText(QCoreApplication.translate("SettingsDialog", u"\u041f\u0440\u0438\u043c\u0435\u043d\u0438\u0442\u044c", None))
    # retranslateUi
