[database]
host = localhost
port = 5433
username = postgres
password = 1
database = 123

[old_database]
host = kaf319bd.education.ru
port = 18349
username = uniskad
password = MAI_Uniskad_2022
database = 51_15_116_32_uniskad2

[logging]
;CRITICAL, FATAL, ERROR, WARN, WARNING, INFO, DEBUG, NOTSET
level = INFO
filename = uniskad.log